query BlogLikes($blogname: String, $method: String, $num: Int, $limit: Int){
  BlogLikes(blog_name: $blogname, method: $method, num: $num, limit: $limit){
    liked_count
    liked_posts {
      post_url
      blog_name
      summary
      caption
      note_count
      timestamp
      thumbnail_url
      video_url
      id
      photos {original_size
        {
          url
        }
    }
  }
  }
}
