query BlogPosts($blogname: String, $postid: Float, $filter: String, $notes_info: Boolean, $reblog_info: Boolean) {
  BlogPosts(blog_name: $blogname, id: $postid, filter: $filter, notes_info: $notes_info, reblog_info: $reblog_info) {
      blog {
        title
      }
      posts {
        summary
        post_url
        thumbnail_url
        video_url
        tags
        timestamp
        liked
        caption
        reblog_key
        video_type
        permalink_url
        source_title
        reblogged_root_id
        reblogged_root_name
        notes {
          type
          timestamp
          blog_name
          followed
          blog_uuid
        }
        photos {
          original_size {
            height
            width
            url
          }
        }
      }
    }
  }
