query UserFollowing($num: Int) {
  UserFollowing(offset: $num) {
    total_blogs
    blogs{
      title
      name
      likes
      share_likes
      followers
      updated
      description
    }
  }
}
