query UserLikes($num: Int, $method: String, $limit: Int){
  UserLikes(num: $num, method: $method , limit: $limit){
    liked_posts {
      blog_name
      note_count
      post_url
      thumbnail_url
      id
      liked
      summary
      timestamp
      photos {
        original_size {
          url
        }
      }
    }
    liked_count
  }
}
